### ISSUE TITLE
Polyfill is broken with IE9 & IE10

### ISSUE THREAD

**Issue by manubb** [webcomponents/template#10]
Maybe that you know about this but the polyfill is broken with IE9 & IE10 since commit 3f03c8e.
For example, with:
```html
<template id="test">
  <div></div>
</template>
```
computing the innerHTML of #test results in an empty string.
By the way, could you please release a npm package of the polyfill?
Regards,
Manuel

**Comment by kapouer** [comment]
@manubb can you reopen that one please ? I'm going to PR that.

**Comment by manubb** [comment]
Reopening issue

**Comment by TimvdLippe** [comment]
We do support IE11, but no earlier versions of IE and at this moment we have no intention to broaden our browser support for IE. Therefore I am closing this issue.
