### ISSUE TITLE
wct is configured by default to run on chrome and firefox, it's pointless

### ISSUE THREAD

**Issue by kapouer** [webcomponents/template#17]
Of course, since the polyfill only do something on *other* browsers.
Please add Edge, IE11 browsers at least to your wct config.

**Comment by TimvdLippe** [comment]
We run these tests on Sauce instead (https://github.com/webcomponents/template/blob/4340a930f28c6d218b74ce246e0c5c72ca68bdc6/.travis.yml#L15) which makes sure we do not regress.
