### ISSUE TITLE
IE11 template not inert -- regression caused by ShadyDOM polyfill

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/template#21]
Using the [V0 polyfill](https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/webcomponents-lite.js), this code

```
        var container = document.createElement('template');
        container.innerHTML = '<x-product data-name="Inert"></x-product>';
```

is inert on IE11.  `<x-product>`'s `createdCallback()` is not called.  

Example [here](https://jeff17robbins.github.io/V1-Issues/inert_polyfill_V0.html).

But using the V1 template polyfill, the same code is not inert on IE11.  (It is inert on Edge and Chrome running the polyfill.)

The constructor is called (and due to V1 semantics being different, the initial `attributeChangedCallback` is also called.)  

Example [here](https://jeff17robbins.github.io/V1-Issues/inert_polyfill.html).

**Comment by Jeff17Robbins** [comment]
The example code's `container.innerHTML = '<x-product data-name="Inert"></x-product>';` calls into this setter

```
        set: function set(text) {
          contentDoc.body.innerHTML = text;
```

which calls the `set` in 

```
  function patch_innerHTML(destination, baseDescriptor) {
    Object.defineProperty(destination, 'innerHTML', {
      enumerable: baseDescriptor.enumerable,
      configurable: true,
      get: baseDescriptor.get,
      set: function set(htmlString) { // <=== this set called
        var _this = this;

        var isConnected$$1 = isConnected(this);

        var removedElements = undefined;
        if (isConnected$$1) {
          removedElements = [];
          walkDeepDescendantElements(this, function (element) {
            if (element !== _this) {
              removedElements.push(element);
            }
          });
        }
```

which calls `isConnected(this)`

The first thing `isConnected()` does is check the node's `isConnected` property.

```
function isConnected(node) {
  var nativeValue = node.isConnected;
```

But the `isConnected` property on `contentDoc.body` is a getter 

```
  get isConnected() {
    var ownerDocument = this.ownerDocument;
    if (ownerDocument && ownerDocument.contains && ownerDocument.contains(this)) return true;
    var ownerDocumentElement = ownerDocument.documentElement;
    if (ownerDocumentElement && ownerDocumentElement.contains && ownerDocumentElement.contains(this)) return true;
```

And that last line's condition `iownerDocumentElement && ownerDocumentElement.contains && ownerDocumentElement.contains(this)` is `true`.  This seems to cause the subsequent upgrade of the meant-to-be-inert template contents.

On browsers with native template elements, there is no getter, and `node.isConnected` is `false`.

**Comment by Jeff17Robbins** [comment]
shadydom/src/patch-builtins.js in https://github.com/webcomponents/shadydom breaks IE11 template polyfill

**Comment by TimvdLippe** [comment]
This appears to be fixed now: http://jsbin.com/gisolix/edit?html,console,output
