### ISSUE TITLE
Setting innerHTML on template in IE11 causes custom elements to upgrade

### ISSUE THREAD

**Issue by sorvell** [webcomponents/template#24]
This looks like the root cause behind https://github.com/webcomponents/shadydom/issues/196.

**Comment by dfreedm** [comment]
This actually seems like a bug in CustomElements. According to the [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#look-up-a-custom-element-definition), documents without a browsing context (`doc.defaultView`) should not upgrade elements.

However, the template polyfill is creating such a document and the CustomElement polyfill is upgrading those elements anyway.

@bicknellr
