### ISSUE TITLE
Template importing breaks when the template is empty

### ISSUE THREAD

**Issue by dfreedm** [webcomponents/template#29]
This is due to the `fixClonedScripts` function using a querySelector with `:not([type])` in the syntax.
If an element or document fragment is empty, the `:not([type])` syntax will throw a `SyntaxException` error.

**Comment by Jeff17Robbins** [comment]
@azakus @valdrinkoshi  I opened this [issue](https://github.com/webcomponents/html-imports/issues/82) because it looks like the html-imports polyfill is exposed to the same IE11 issue (`:not([type])` applied to a potentially empty `template.content`.
