### ISSUE TITLE
Template.js shouldn't modify `Node.prototype.cloneNode`

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/template#4]
_From @mhkeller on July 15, 2016 21:36_

Template.js overwrites the `cloneNode` method of `Node.prototype` on [line 216](https://github.com/webcomponents/webcomponentsjs/blob/bffb86c750039b54ca9d3d3df5c46426cb4ab570/src/Template/Template.js#L216) of Template.js.

This causes problems with libraries that use native `Node.cloneNode`. 

This should be fixed to either create a new prototype method or replace `Node.prototype.cloneNode` with `nativeCloneNode` when this script is finished.

_Copied from original issue: webcomponents/webcomponentsjs#578_

**Comment by TimvdLippe** [comment]
I think this has been fixed now: https://github.com/webcomponents/template/blob/ea17aae3e0be42426e053beffe7202a637580b03/template.js#L28-L30
