### ISSUE TITLE
Edge 17.134 Unable to set property 'innerHTML' of undefined or null reference

### ISSUE THREAD

**Issue by ruud** [webcomponents/template#41]
New version of Edge 17, is causing problems accessing the template during the connectedCallback using Polymer version 2.6.0 and webcomponentsJS 1.2.0

Note: Edge 16 does not have this issue.

<img width="1004" alt="screen shot 2018-05-01 at 8 13 39 pm" src="https://user-images.githubusercontent.com/28245/39486912-fda60d58-4d7d-11e8-9fe7-d64ef3147d50.png">

**Comment by ruud** [comment]
related issue: https://github.com/webcomponents/webcomponentsjs/issues/923

**Comment by ruud** [comment]
Probable root cause: Edge has broken fragment cloning which means you cannot clone template.content. That's why the polyfill was forced in the web component loader. This mechanism is not working for Edge 17. When added an extra browser check to the loader fixes this problem.

**Comment by AdamDotNet** [comment]
@TimvdLippe - your request from webcomponents/webcomponentsjs#923
Using Edge 17.17134
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>webcomponents/template Edge 17 Check</title>
    </head>
    <body>
        <div id="results"></div>
        <script>
            var brokenDocFragment = !(document.createDocumentFragment().cloneNode() instanceof DocumentFragment);
            var needsTemplate = (typeof HTMLTemplateElement === 'undefined');
            var results = document.getElementById('results');

            var needsCloningResult = needsCloning();
            results.innerHTML = `needsCloningResult = ${needsCloningResult}`;

            function needsCloning() {
                if (!needsTemplate) {
                    var t = document.createElement('template');
                    var t2 = document.createElement('template');
                    t2.content.appendChild(document.createElement('div'));
                    t.content.appendChild(t2);
                    var clone = t.cloneNode(true);
                    return (clone.content.childNodes.length === 0 || clone.content.firstChild.content.childNodes.length === 0
                        || brokenDocFragment);
                }
            }
        </script>
    </body>
</html>
```

Writes to the div: `needsCloningResult = true`
`brokenDocFragment` is `false`
`needsTemplate` is `false`
`clone.content.childNodes.length === 0` returns `true`
`clone.content.firstChild` is `null`

**Comment by TimvdLippe** [comment]
Awesome thanks. I will debug it this weekend and see if I can fix it :)

**Comment by TimvdLippe** [comment]
Could you confirm that https://github.com/webcomponents/webcomponentsjs/pull/931 has fixed this issue?

**Comment by Westbrook** [comment]
✋ @TimvdLippe my tests rather like this change! I'm gonna do some more testing with other repos, but very excited to have my Edge 17 tests looking greener here.

Will there be a version of this released into the 1.x series as some point? Possibly soon?

**Comment by TimvdLippe** [comment]
@azakus I think backporting this fix to 1.x makes sense, WDYT?

**Comment by dfreedm** [comment]
Yeah making a 1.x release with updated polyfills is something I need to do 👍

**Comment by TimvdLippe** [comment]
V1 published per https://github.com/webcomponents/webcomponentsjs/issues/948 :tada:
