### ISSUE TITLE
[important] Release new version with the latest bug fixes

### ISSUE THREAD

**Issue by smalluban** [webcomponents/template#43]
Hey! I think it would be great to release a new version of the polyfill with the latest bug fixes. It is important because of support `<table>` element family. Actually, it is the last failing test in IE11 for https://github.com/hybridsjs/hybrids library. With the code from `master` branch all test pass.

Also, please consider using tags and push them to the repository, as the latest version on GitHub is https://github.com/webcomponents/template/releases/tag/v1.0.0-rc.1, but on NPM is `1.2.4`. It is not so hard, so if you need help I can contribute.

**Comment by TimvdLippe** [comment]
We release regularly and the next release will be published by @azakus this week.

**Comment by smalluban** [comment]
Great news :), but what do you mean regularly? Is it every week or month (if there is some change in the code of course)?

**Comment by TimvdLippe** [comment]
Normally every 2 weeks, but Google IO made us skip 1 release cycle.

**Comment by smalluban** [comment]
Thanks for clarification. I think there is no more things to discuss, so I am closing the issue.
