### ISSUE TITLE
Template polyfill seems to empty the template element content

### ISSUE THREAD

**Issue by toufali** [webcomponents/template#47]
On IE11, `import '@webcomponents/template'` seems to load successfully, except it empties the template content that I have in HTML.  The code below then fails in IE11 with this error:
> Unable to get property 'cloneNode' of undefined or null reference

```
const ageTmp = document.getElementById('age-tmp')
const ag = document.createElement('div')
ag.appendChild(ageTmp.content.cloneNode(true))
```

Pre-polyfill (import commented out):
![pre-poly](https://user-images.githubusercontent.com/14863500/41933022-8cfc8790-7937-11e8-8ed8-2c91f8b4e51e.png)

Post-polyfill:
![post-poly](https://user-images.githubusercontent.com/14863500/41933045-9c511c4c-7937-11e8-8946-f5b1e770ead5.png)

I've also tested putting the script tag directly in the head with the same result - template element's content is emptied.  Native template code (Chrome, FF, etc) works fine.

**Comment by TimvdLippe** [comment]
Could you provide a JSBin that shows the issue?

**Comment by toufali** [comment]
Here's a Codepen demonstrating the issue - testing on IE11, the content of the template is removed, and IE then hangs on an `undefined or null reference` error:

https://codepen.io/anon/pen/LBPJrb?editors=1011

(See bottom of JS panel for 4 lines cloning and appending the template node.)

JSBin was behaving strangely (security issues running polyfill and it would also remove HTML template tags from source code) - here's the link anyway:

https://jsbin.com/yorojipeco/1/edit?html,js,console,output

**Comment by kapouer** [comment]
It doesn't help much but i can confirm "Hello World" disappears on IE11.
EDIT: https://codepen.io/anon/pen/LBPJrb?editors=1011 fails with 
`Unable to get property 'cloneNode' of undefined or null reference` doing this:
`tmp.content.cloneNode(true)`

**Comment by TimvdLippe** [comment]
Okay, I took a look at the source and the following is the case. We upgrade all templates in the main document on `DOMContentLoaded`: https://github.com/webcomponents/template/blob/45b7a7ef27fe5d4352b9a8fbc2ee5d4cab5fddff/template.js#L316-L319

This is a known limitation, as it is the first ever correct point that the polyfill can do its work. It is the first provided timepoint that we can be sure the main document is loaded.

However, your code is IN the main document. This means it is strictly before this timepoint. Sadly this is a limitation of the polyfill. I will go ahead and document this.

**Comment by toufali** [comment]
Thanks for looking into this.  Bummer! 
In case anyone else ends up here, I was able to use this polyfill instead with full success: https://www.npmjs.com/package/template-polyfill

**Comment by TimvdLippe** [comment]
@HandsomeMedia That polyfill is 2 years old and has multiple other issues, thus I would not advise to use that polyfill. Instead, this known limitation can be worked around by waiting for `DOMContentLoaded`, which seems less of a hassle imo.
