### ISSUE TITLE
Support really old browsers

### ISSUE THREAD

**Issue by dfreedm** [webcomponents/template#50]
Some customers have been asking for support for _just_ the template polyfill on really old devices.
The issue with these devices seem to revolve around `childNodes` and `innerHTML` getters being magical instance properties and not present on the prototype chain.

For these browsers, it should be enough to fake out a property descriptor that calls the instance methods.

**Comment by Malvoz** [comment]
Which browsers does this polyfill currently cover? It'd be great if there was a compatibility table.
