### ISSUE TITLE
reconsider support for earlier versions of IE! IE9+

### ISSUE THREAD

**Issue by TheDevelolper** [webcomponents/template#53]
Hi there, 
I would really like to use your library but I have client restrictions. Many companies often use older versoins of IE. They also have support contracts that costs them 10,000's to upgrade their browsers. 

I think you would reach a much larger audience if you consider supporting IE9 as there are many businesses and government organisations who simply won't upgrade yet. 

Please don't just close this issue off... consider it. 

I'm happy to assist you in any way that I can.

**Comment by TimvdLippe** [comment]
@KiransHub We are always open for PRs that can solve this. It will depend on the amount of added complexity. If it requires a couple of line changes, sure! If it requires a lot of work, it is probably not worth the maintenance cost for us.

So feel free to work on this and open a PR and we can go from there :smile:

**Comment by TheDevelolper** [comment]
@TimvdLippe I managed to get my own webcomponents working in IE9. It uses Angular and a bunch of polyfills! It's a little hacked together but it works. I also have a build script that will go through the generated javascript files and turn all consts back into vars (for ie9 & 10). 

https://github.com/KiransHub/AngularWebComponentsForIE9

**Comment by TimvdLippe** [comment]
@KiransHub Your version of the polyfills is webcomponents v1. The latest version of the polyfills is v2 (2.1.3 to precise: https://www.npmjs.com/package/@webcomponents/webcomponentsjs)

Also, we publish all of our publish in ES5 compatible, so there should be no `const` in the final bundles.

**Comment by TheDevelolper** [comment]
@TimvdLippe okay I will give that a go.. I might be able to remove some of my own custom pollyfills then

**Comment by dfreedm** [comment]
This issues appears to be very old, so I'm going to close it. If you think this is still important, please file a new issue on https://github.com/webcomponents/polyfills
