### ISSUE TITLE
Update package name to match scoping convention for updated polyfills

### ISSUE THREAD

**Issue by treshugart** [webcomponents/template#8]
I've been using `@webcomponents/template` as the dependency key to install this and NPM is failing because the name in the package.json doesn't match that. I'm assuming that this will eventually be released as `template` under the `@webcomponents` scope and this fixes any issue with NPM failing on that in the future.

**Comment by TimvdLippe** [comment]
This appears to be fixed now: https://github.com/webcomponents/template/blob/4340a930f28c6d218b74ce246e0c5c72ca68bdc6/package.json#L2
